#!/bin/bash
ls -la                                                                        

total 44                                                                                                                                                 

drwxr-xr-x 2 root root 233 Dec  7 15:55 .                                                                                                                

drwxr-xr-x 4 root root 107 Dec  7 15:16 ..                                                                                                               

-rwxr-xr-x 1 root root  32 Dec  7 13:57 0-hello_world                                                                                                    

-rwxr-xr-x 1 root root  31 Dec  7 14:21 1-confused_smiley                                                                                                

-rwxr-xr-x 1 root root  28 Dec  7 14:35 2-hellofile                                                                                                      

-rwxr-xr-x 1 root root  39 Dec  7 14:44 3-twofiles                                                                                                       

-rwxr-xr-x 1 root root  35 Dec  7 14:56 4-lastlines                                                                                                      

-rw-r--r-- 1 root root  35 Dec  7 15:01 5-firstlines                                                                                                     

-rw-r--r-- 1 root root  22 Dec  7 15:32 6-third_line                                                                                                     

-rw-r--r-- 1 root root  12 Dec  7 15:42 7-file                                                                                                           

-rw-r--r-- 1 root root  12 Dec  7 15:45 8-cwd_state                                                                                                      

-rw-r--r-- 1 root root 780 Dec  7 15:35 iacta                                                                                                            

-rw-r--r-- 1 root root   0 Dec  7 15:48 ls_cwd_content                                                                                                   

-rw-r--r-- 1 root root  35 Dec  7 13:31 README.md
